import { NextResponse } from "next/server";
import * as z from "zod";
import { runAgent } from "@/core/agent.js";
import { rateLimit } from "@/lib/rate-limit.js";

const MessageSchema=z.object({id:z.string().optional(),role:z.enum(["user","assistant","system","tool"]),content:z.union([z.string(),z.array(z.unknown())]).optional(),parts:z.array(z.unknown()).optional(),createdAt:z.union([z.string(),z.date()]).optional()}).passthrough();
const SettingsSchema=z.object({model:z.string().max(120).optional(),systemPrompt:z.string().max(12000).optional(),temperature:z.number().min(0).max(1).optional()}).optional().default({});
const RequestSchema=z.object({messages:z.array(MessageSchema).min(1).max(200),userId:z.string().max(128).optional().default("anonymous"),sessionId:z.string().max(128).optional(),settings:SettingsSchema});
export async function POST(request){const ip=request.headers.get("x-forwarded-for")?.split(",")[0]?.trim()??request.headers.get("x-real-ip")??"unknown";const limit=rateLimit(ip);if(!limit.allowed)return NextResponse.json({error:"Too many requests",retryAfter:limit.retryAfter},{status:429});let raw;try{raw=await request.json()}catch{return NextResponse.json({error:"Invalid JSON"},{status:400})}const parsed=RequestSchema.safeParse(raw);if(!parsed.success)return NextResponse.json({error:"Invalid request",details:parsed.error.issues},{status:400});const {messages,userId,sessionId,settings}=parsed.data;let result;try{result=await runAgent({messages,userId,sessionId,runtimeSettings:settings})}catch(err){console.error("[/api/chat] runAgent failed:",err);return NextResponse.json({error:"Agent failed to respond",message:err.message||"Something went wrong"},{status:500})}const stream=new ReadableStream({async start(controller){const enc=new TextEncoder();const send=o=>{try{controller.enqueue(enc.encode(`data: ${JSON.stringify(o)}\n\n`))}catch{}};try{for await(const event of result.fullStream){if(event.type==="text-delta")send({type:"text-delta",delta:event.textDelta??event.text??""});else if(event.type==="tool-call")send({type:"tool-call",toolName:event.toolName,args:event.args??event.input??{}});else if(event.type==="tool-result")send({type:"tool-result",toolName:event.toolName,result:event.result})}}catch(err){console.error("[/api/chat] stream error:",err);send({type:"error",message:err.message})}finally{controller.close()}}});return new Response(stream,{headers:{"Content-Type":"text/event-stream","Cache-Control":"no-cache","Connection":"keep-alive"}})}
