"use client";
import { useState, useRef, useEffect, useCallback } from "react";
import Link from "next/link";
import { MessageBubble } from "@/components/chat/MessageBubble.jsx";
import { InputBar } from "@/components/chat/InputBar.jsx";
import { TypingIndicator } from "@/components/chat/TypingIndicator.jsx";
import { SuggestedPrompts } from "@/components/chat/SuggestedPrompts.jsx";
import { AgentHeader } from "@/components/chat/AgentHeader.jsx";

export function ChatWindow({ agentName, agentColor, agentInitials, welcomeMessage, suggestedPrompts, showToolCalls, showBranding, userId = "anonymous" }) {
  const [messages, setMessages] = useState([]); const [inputValue,setInputValue]=useState(""); const [isLoading,setIsLoading]=useState(false); const [error,setError]=useState(null); const bottomRef=useRef(null); const abortRef=useRef(null);
  useEffect(()=>{bottomRef.current?.scrollIntoView({behavior:"smooth"})},[messages,isLoading]);
  const stop=useCallback(()=>{abortRef.current?.abort();setIsLoading(false)},[]);
  const sendMessage=useCallback(async(text)=>{ if(!text?.trim()||isLoading)return; setError(null); const uid="u-"+Date.now(); setMessages(p=>[...p,{id:uid,role:"user",content:text,parts:[{type:"text",text}]}]); setIsLoading(true); const ctrl=new AbortController(); abortRef.current=ctrl;
    try { const apiMessages=[...messages.map(m=>({id:m.id,role:m.role,content:m.content??"",parts:m.parts??[{type:"text",text:m.content??""}]})),{id:uid,role:"user",content:text,parts:[{type:"text",text}]}]; let settings={}; try{settings=JSON.parse(localStorage.getItem("agentkit-settings")||"{}")}catch{}
      const res=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({messages:apiMessages,userId,settings}),signal:ctrl.signal}); if(!res.ok){const e=await res.json().catch(()=>({}));throw new Error(e.message??e.error??`HTTP ${res.status}`)}
      const aid="a-"+Date.now(); setMessages(p=>[...p,{id:aid,role:"assistant",content:"",parts:[{type:"text",text:""}]}]); const reader=res.body.getReader(),decoder=new TextDecoder();let acc="",toolParts=[],buf=""; const update=(text,tools)=>setMessages(p=>p.map(m=>m.id===aid?{...m,content:text,parts:[{type:"text",text},...tools]}:m));
      while(true){const {done,value}=await reader.read();if(done)break;buf+=decoder.decode(value,{stream:true});const lines=buf.split("\n");buf=lines.pop()??"";for(const line of lines){if(!line.startsWith("data: "))continue;try{const o=JSON.parse(line.slice(6));if(o.type==="text-delta"&&o.delta){acc+=o.delta;update(acc,toolParts)}else if(o.type==="tool-call"){toolParts=[...toolParts,{type:"tool-invocation",state:"call",toolName:o.toolName,args:o.args??{},toolInvocation:{toolName:o.toolName,args:o.args??{},state:"call"}}];update(acc,toolParts)}else if(o.type==="tool-result"){toolParts=toolParts.map(p=>p.type==="tool-invocation"&&p.toolName===o.toolName&&p.state==="call"?{...p,state:"result",toolInvocation:{...p.toolInvocation,state:"result",result:o.result}}:p);update(acc,toolParts)}else if(o.type==="error")setError(o.message??"Stream error")}catch{}}}
    }catch(err){if(err.name!=="AbortError"){console.error("[chat]",err);setError(err.message??"Something went wrong")}}finally{setIsLoading(false)} },[messages,isLoading,userId]);
  const submit=useCallback(e=>{e?.preventDefault();const t=inputValue.trim();if(!t)return;setInputValue("");sendMessage(t)},[inputValue,sendMessage]); const isEmpty=messages.length===0;
  return <div className="flex h-screen flex-col bg-background"><div className="relative"><AgentHeader name={agentName} color={agentColor} initials={agentInitials} isLoading={isLoading}/><Link href="/settings" className="absolute right-4 top-1/2 -translate-y-1/2 rounded-lg border bg-background px-3 py-2 text-sm hover:bg-muted">⚙ Settings</Link></div><div className="chat-scroll flex-1 overflow-y-auto"><div className="mx-auto max-w-3xl px-4 py-6">{isEmpty&&<div className="flex flex-col items-center justify-center py-16 text-center"><div className="mb-4 flex h-16 w-16 items-center justify-center rounded-2xl text-2xl font-semibold text-white shadow-sm" style={{backgroundColor:agentColor}}>{agentInitials}</div><h1 className="mb-2 text-2xl font-semibold">{agentName}</h1><p className="mb-8 max-w-md text-muted-foreground">{welcomeMessage}</p>{suggestedPrompts?.length>0&&<SuggestedPrompts prompts={suggestedPrompts} onSelect={setInputValue} color={agentColor}/>}</div>}{messages.map(m=><MessageBubble key={m.id} message={m} agentName={agentName} agentColor={agentColor} agentInitials={agentInitials} showToolCalls={showToolCalls}/>)}{isLoading&&messages.at(-1)?.role==="user"&&<TypingIndicator agentColor={agentColor} agentInitials={agentInitials}/>} {error&&<div className="my-4 rounded-lg border border-destructive/20 bg-destructive/5 px-4 py-3 text-sm text-destructive">{error}</div>}<div ref={bottomRef}/></div></div><div className="border-t bg-background/80"><div className="mx-auto max-w-3xl px-4 py-4"><InputBar input={inputValue} onChange={e=>setInputValue(e.target.value)} onSubmit={submit} isLoading={isLoading} onStop={stop} agentColor={agentColor}/>{showBranding&&<p className="mt-2 text-center text-xs text-muted-foreground">AgentKit</p>}</div></div></div>;
}
