"use client";
import {useState,useRef,useEffect,useCallback} from "react";
import Link from "next/link";
import {InputBar} from "@/components/chat/InputBar.jsx";

const STORE="agentkit-conversations-v3";
const ACTIVE="agentkit-active-conversation-v3";
const makeId=()=>`${Date.now()}-${Math.random().toString(36).slice(2)}`;
const fresh=()=>({id:makeId(),title:"New chat",updatedAt:Date.now(),messages:[]});
function Glyph({state="idle"}){return <span className={`living-glyph glyph-${state}`} aria-hidden="true"><i/><b/></span>}
function readStore(){try{const x=JSON.parse(window.localStorage.getItem(STORE)||"[]");return Array.isArray(x)?x:[]}catch{return[]}}
function writeStore(x){try{window.localStorage.setItem(STORE,JSON.stringify(x))}catch{}}
function SafeMessage({message}){const user=message?.role==="user";const text=typeof message?.content==="string"?message.content:"";if(!text)return null;return <div className={user?"living-user":"living-assistant"}>{!user&&<div className="living-identity"><Glyph/><span>Agent</span></div>}<div className="living-safe-message" dir="auto" style={{whiteSpace:"pre-wrap"}}>{text}</div></div>}

export function ChatWindow({agentName="AgentKit",welcomeMessage="How can I help?",suggestedPrompts=[],showBranding=true,userId="anonymous"}){
 const [mounted,setMounted]=useState(false),[messages,setMessages]=useState([]),[input,setInput]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[convos,setConvos]=useState([]),[active,setActive]=useState(null),[drawer,setDrawer]=useState(false),[state,setState]=useState("idle"),[search,setSearch]=useState("");
 const abort=useRef(null),activeRef=useRef(null),bottom=useRef(null);
 useEffect(()=>{setMounted(true);let list=readStore();let id=null;try{id=window.localStorage.getItem(ACTIVE)}catch{}let c=list.find(v=>v&&v.id===id);if(!c){c=fresh();list=[c,...list];writeStore(list)}setConvos(list);setActive(c.id);activeRef.current=c.id;setMessages(Array.isArray(c.messages)?c.messages:[]);try{window.localStorage.setItem(ACTIVE,c.id)}catch{}},[]);
 useEffect(()=>{activeRef.current=active},[active]);
 useEffect(()=>{if(mounted)bottom.current?.scrollIntoView({block:"end"})},[messages,busy,mounted]);
 const persist=useCallback(next=>{setMessages(next);const id=activeRef.current;if(!id)return;setConvos(prev=>{const list=prev.map(c=>{if(c.id!==id)return c;const first=next.find(m=>m?.role==="user"&&typeof m.content==="string");return {...c,messages:next,updatedAt:Date.now(),title:c.title==="New chat"&&first?first.content.slice(0,48):c.title}});writeStore(list);return list})},[]);
 const newChat=()=>{const c=fresh();setConvos(prev=>{const list=[c,...prev];writeStore(list);return list});setActive(c.id);activeRef.current=c.id;setMessages([]);setInput("");setError("");setDrawer(false);try{window.localStorage.setItem(ACTIVE,c.id)}catch{}};
 const choose=c=>{if(!c)return;setActive(c.id);activeRef.current=c.id;setMessages(Array.isArray(c.messages)?c.messages:[]);setDrawer(false);try{window.localStorage.setItem(ACTIVE,c.id)}catch{}};
 const remove=(e,id)=>{e.preventDefault();e.stopPropagation();setConvos(prev=>{let list=prev.filter(c=>c.id!==id);if(!list.length)list=[fresh()];writeStore(list);if(activeRef.current===id)queueMicrotask(()=>choose(list[0]));return list})};
 const stop=()=>{abort.current?.abort();setBusy(false);setState("idle")};
 const send=useCallback(async text=>{const clean=String(text||"").trim();if(!clean||busy)return;setError("");const user={id:makeId(),role:"user",content:clean};const before=[...messages,user];persist(before);setBusy(true);setState("thinking");const controller=new AbortController();abort.current=controller;
 try{let settings={};try{settings=JSON.parse(window.localStorage.getItem("agentkit-settings")||"{}")}catch{}const res=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({messages:before.map(m=>({role:m.role,content:m.content})),userId,sessionId:activeRef.current,settings}),signal:controller.signal});if(!res.ok)throw new Error(`Request failed (${res.status})`);if(!res.body)throw new Error("No response stream");const assistant={id:makeId(),role:"assistant",content:""};let current=[...before,assistant],acc="",buffer="";persist(current);const reader=res.body.getReader(),decoder=new TextDecoder();while(true){const chunk=await reader.read();if(chunk.done)break;buffer+=decoder.decode(chunk.value,{stream:true});const lines=buffer.split("\n");buffer=lines.pop()||"";for(const line of lines){if(!line.startsWith("data: "))continue;try{const event=JSON.parse(line.slice(6));if(event.type==="text-delta"&&typeof event.delta==="string"){setState("writing");acc+=event.delta;current=current.map(m=>m.id===assistant.id?{...m,content:acc}:m);persist(current)}else if(event.type==="tool-call"){setState(String(event.toolName||"").includes("search")?"searching":"tool")}else if(event.type==="tool-result"){setState("reading")}else if(event.type==="error"){throw new Error(event.message||"Agent error")}}catch(parseError){if(parseError instanceof SyntaxError)continue;throw parseError}}}setState("success");window.setTimeout(()=>setState("idle"),600)}catch(e){if(e?.name!=="AbortError"){setError(e?.message||"Something went wrong");setState("error")}}finally{setBusy(false)}},[messages,busy,userId,persist]);
 const submit=e=>{e?.preventDefault?.();const text=input.trim();if(!text||busy)return;setInput("");send(text)};
 const list=convos.filter(c=>String(c?.title||"New chat").toLowerCase().includes(search.toLowerCase()));
 if(!mounted)return <div className="living-shell"><main className="living-main"><div className="living-welcome"><Glyph/><h1>{agentName}</h1></div></main></div>;
 return <div className="living-shell">
 <aside className={`living-side ${drawer?"living-side-open":""}`}><div className="living-brand"><div className="living-brand-left"><Glyph state={state}/><div><strong>AgentKit</strong><small><i/> Ready</small></div></div><button type="button" className="living-close" onClick={()=>setDrawer(false)}>×</button></div><button type="button" className="living-new" onClick={newChat}><span>＋</span> New Chat</button><div className="living-search">⌕ <input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search conversations..."/></div><div className="living-history">{list.map(c=><button type="button" key={c.id} onClick={()=>choose(c)} className={c.id===active?"active":""}><span className="dot"/><span>{String(c.title||"New chat")}</span><em onClick={e=>remove(e,c.id)}>×</em></button>)}</div><div className="living-bottom"><Link href="/settings">Tools & Extensions</Link><Link href="/settings">Settings</Link></div></aside>
 <main className="living-main"><header className="living-head"><div className="living-head-left"><button type="button" className="living-menu" onClick={()=>setDrawer(true)}>☰</button><Glyph state={state}/><b>Agent</b><span className="living-online"><i/> {busy?state:"Online"}</span></div><div className="living-head-actions"><Link href="/settings" className="living-model">Model ▾</Link><button type="button" onClick={()=>persist([])}>Clear</button></div></header>
 <section className="living-chat"><div className="living-chat-inner">{messages.length===0&&<div className="living-welcome"><Glyph state={state}/><h1>{agentName}</h1><p>{welcomeMessage}</p>{Array.isArray(suggestedPrompts)&&suggestedPrompts.length>0&&<div className="flex flex-wrap justify-center gap-2">{suggestedPrompts.map((p,i)=><button type="button" key={`${i}-${p}`} onClick={()=>setInput(String(p))}>{String(p)}</button>)}</div>}</div>}{messages.map((m,i)=><SafeMessage key={m?.id||i} message={m}/>)}{busy&&<div className="living-tool"><span>◌</span><b>{state}…</b></div>}{error&&<div className="living-error">{error} <button type="button" onClick={()=>setError("")}>×</button></div>}<div ref={bottom}/></div></section>
 <footer className="living-composer"><div className="living-composer-inner"><div className="living-input-wrap"><button type="button" className="living-plus">＋</button><InputBar input={input} onChange={e=>{setInput(e.target.value);if(!busy)setState(e.target.value?"attentive":"idle")}} onSubmit={submit} isLoading={busy} onStop={stop} agentColor="#b4c5ff"/></div><div className="living-utils"><span>◎ Web Search</span><small>{showBranding?"AgentKit can make mistakes. Verify important information.":""}</small></div></div></footer></main></div>
}
