/**
 * lib/env.js — Validated environment variables
 */
import * as z from "zod";
const serverSchema=z.object({
 NODE_ENV:z.enum(["development","test","production"]).default("development"),
 AI_PROVIDER:z.enum(["gemini","nvidia","openai","anthropic","groq"]).default("gemini"),
 AI_MODEL:z.string().default("gemini-3.8-flash"), AI_TEMPERATURE:z.coerce.number().min(0).max(1).default(0.7), AI_MAX_TOKENS:z.coerce.number().min(100).max(32000).default(4096),
 GOOGLE_GENERATIVE_AI_API_KEY:z.string().optional(), NVIDIA_API_KEY:z.string().optional(), OPENAI_API_KEY:z.string().optional(), ANTHROPIC_API_KEY:z.string().optional(), GROQ_API_KEY:z.string().optional(),
 SUPABASE_URL:z.string().url().optional(),SUPABASE_ANON_KEY:z.string().optional(),SUPABASE_SERVICE_ROLE_KEY:z.string().optional(),TAVILY_API_KEY:z.string().optional(),RESEND_API_KEY:z.string().optional(),EMAIL_FROM:z.string().email().optional(),TELEGRAM_BOT_TOKEN:z.string().optional(),GOOGLE_CLIENT_ID:z.string().optional(),GOOGLE_CLIENT_SECRET:z.string().optional(),GOOGLE_REDIRECT_URI:z.string().url().optional(),E2B_API_KEY:z.string().optional(),NOTION_TOKEN:z.string().optional(),GITHUB_TOKEN:z.string().optional(),SLACK_BOT_TOKEN:z.string().optional(),SLACK_WEBHOOK_URL:z.string().url().optional(),TELEGRAM_CHAT_ID:z.string().optional(),RATE_LIMIT_PER_MINUTE:z.coerce.number().min(1).max(1000).default(20),CRON_SECRET:z.string().optional(),OWNER_EMAIL:z.string().email().optional(),REGISTRY_ENABLED:z.string().transform(v=>v==="true").default("false")
});
const clientSchema=z.object({NEXT_PUBLIC_AGENT_NAME:z.string().min(1).default("My Agent"),NEXT_PUBLIC_AGENT_DESCRIPTION:z.string().default("A helpful AI assistant"),NEXT_PUBLIC_AGENT_COLOR:z.string().regex(/^#[0-9A-Fa-f]{6}$/).default("#0F6E56"),NEXT_PUBLIC_AGENT_INITIALS:z.string().min(1).max(3).default("AG"),NEXT_PUBLIC_AGENT_WELCOME:z.string().default("Hi! How can I help you today?"),NEXT_PUBLIC_AGENT_THEME:z.enum(["light","dark","system"]).default("system"),NEXT_PUBLIC_SHOW_BRANDING:z.string().transform(v=>v!=="false").default("true"),NEXT_PUBLIC_APP_URL:z.string().url().default("http://localhost:3000")});
function parseServerEnv(){const result=serverSchema.safeParse(process.env);if(!result.success)throw new Error("Invalid environment variables: "+result.error.issues.map(i=>`${i.path.join(".")}: ${i.message}`).join("; "));const env=result.data;/* Runtime provider can be selected in Settings, so do not require its key at build time. */return env;}
function parseClientEnv(){const result=clientSchema.safeParse({NEXT_PUBLIC_AGENT_NAME:process.env.NEXT_PUBLIC_AGENT_NAME,NEXT_PUBLIC_AGENT_DESCRIPTION:process.env.NEXT_PUBLIC_AGENT_DESCRIPTION,NEXT_PUBLIC_AGENT_COLOR:process.env.NEXT_PUBLIC_AGENT_COLOR,NEXT_PUBLIC_AGENT_INITIALS:process.env.NEXT_PUBLIC_AGENT_INITIALS,NEXT_PUBLIC_AGENT_WELCOME:process.env.NEXT_PUBLIC_AGENT_WELCOME,NEXT_PUBLIC_AGENT_THEME:process.env.NEXT_PUBLIC_AGENT_THEME,NEXT_PUBLIC_SHOW_BRANDING:process.env.NEXT_PUBLIC_SHOW_BRANDING,NEXT_PUBLIC_APP_URL:process.env.NEXT_PUBLIC_APP_URL});return result.success?result.data:clientSchema.parse({});}
export const serverEnv=typeof window==="undefined"?parseServerEnv():null;export const clientEnv=parseClientEnv();export const agentIdentity={name:clientEnv.NEXT_PUBLIC_AGENT_NAME,description:clientEnv.NEXT_PUBLIC_AGENT_DESCRIPTION,color:clientEnv.NEXT_PUBLIC_AGENT_COLOR,initials:clientEnv.NEXT_PUBLIC_AGENT_INITIALS,welcome:clientEnv.NEXT_PUBLIC_AGENT_WELCOME,theme:clientEnv.NEXT_PUBLIC_AGENT_THEME,showBranding:clientEnv.NEXT_PUBLIC_SHOW_BRANDING,appUrl:clientEnv.NEXT_PUBLIC_APP_URL};
